- lib/cmds/extension_cmds/utils/prepare-data.js
- test/unit/cmds/extension_cmds/create.test.js
Easy up developing UI extensions
If `src` or `srcdoc` args set via CLI, any of these values get removed from the descriptor file to allow overwriting and avoid `Must contain exactly one of: src, srcdoc`
> fix(extensions): overwrite src & srcdoc via cmd args

- .babelrc
- package-lock.json
- package.json
Drops unnecessary dependencies related to babel
* `babel-runtime` and `babel-plugin-transform-runtime` can be dropped since the minimum Node.js version is 6 which already supports generators (regenerator support was the only part of `babel-plugin-transform-runtime` that was enabled)
* `babel-types` and `babel-template` aren't used. They're still indirect dependencies,
Less dependencies is better. It doesn't have any impact on the built code.
> Drop unnecessary babel dependencies 

- lib/cmds/space_cmds/migration.js
This PR fixes the import of the `contentful-migration` library.
In v0.12.0 of the Contentful CLI, when running commands with `contentful space migration`, an error is thrown:
```
Error: Cannot find module 'contentful-migration-cli/built/bin/cli'
```
This error was introduced when `contentful-migration-cli` was renamed to `contentful-migration`.
> Fix import of contentful-migration

- lib/cmds/boilerplate.js
- lib/cmds/content-type_cmds/get.js
- lib/cmds/content-type_cmds/list.js
- lib/cmds/extension_cmds/create.js
- lib/cmds/extension_cmds/delete.js
- lib/cmds/extension_cmds/get.js
- lib/cmds/extension_cmds/list.js
- lib/cmds/extension_cmds/update.js
- lib/cmds/logout.js
- lib/cmds/space_cmds/accesstoken_cmds/create.js
- lib/cmds/space_cmds/accesstoken_cmds/list.js
- lib/cmds/space_cmds/environment_cmds/create.js
- lib/cmds/space_cmds/environment_cmds/delete.js
- lib/cmds/space_cmds/environment_cmds/list.js
- lib/cmds/space_cmds/environment_cmds/use.js
- lib/cmds/space_cmds/generate_cmds/migration.js
- lib/cmds/space_cmds/list.js
- lib/cmds/space_cmds/use.js
After the `--management-token` parameter was added to the `space list` command, the `assertLoggedIn` function wasn't updated to receive the `argv` parameter, so it will always fail if no default token is found in the `.contentfulrc.json` file
> Make logged-in assertion check in command parameters

- lib/cmds/content-type_cmds/get.js
Introduce the `environmentId` to the `get` command. 
Solves what describe in #65
> Fix #65 provide environment in the get cmd

- package.json
- test/unit/cmds/space_cmds/create.test.js
The jest mock pr broke some tests since i forgot to rebase on master.
This fixes it + runs the jest tests on push in the right context + unit tests only (for now)
> tests(unit): fix merge issues from tests

- lib/cmds/extension_cmds/create.js
- lib/cmds/extension_cmds/delete.js
- lib/cmds/extension_cmds/get.js
- lib/cmds/extension_cmds/list.js
- lib/cmds/extension_cmds/update.js
From issue https://github.com/contentful/contentful-cli/issues/96 this allows passing the CMA token via cli for extension commands
```
contentful extension list --space-id $CONTENTFUL_SPACE --management-token $CONTENTFUL_CMA_TOKEN
```
If the user does not perform `contentful login`, extension commands can be used by passing a `--management-Token` option, ex.
```
contentful extension list --space-id $CONTENTFUL_SPACE --management-token $CONTENTFUL_CMA_TOKEN
```
Command actually throws because the management token for `extension_cmds` commands is not parsed and applied the same way that is for `space_cmds`
```
contentful extension list --space-id $CONTENTFUL_SPACE --management-token $CONTENTFUL_CMA_TOKEN
🚨  Error: Expected parameter accessToken
│ TypeError: Expected parameter accessToken …
```
> update extension commands with cli option for access token

- docs/space/README.md
This PR adds a missing environment link to the space docs page
> add link to env doc page from space docs page

- lib/cmds/space_cmds/generate_cmds/migration.js
Add option to generate migration command to pass management token.
The generate migration command does not have an option to pass in the management token; and thus exhibits the same error as seen in the environment command described in #110
> fix(generate migration): add management-token

- docs/extension/create/README.md
- docs/extension/update/README.md
- lib/cmds/extension_cmds/create.js
- lib/cmds/extension_cmds/update.js
- lib/cmds/extension_cmds/utils/assertions.js
- lib/cmds/extension_cmds/utils/log-as-table.js
- test/integration/cmds/extension/create.test.js
- test/integration/cmds/extension/update.test.js
- test/unit/cmds/extension_cmds/__snapshots__/create.test.js.snap
- test/unit/cmds/extension_cmds/__snapshots__/update.test.js.snap
- test/unit/cmds/extension_cmds/create.test.js
- test/unit/cmds/extension_cmds/update.test.js
`fieldsTypes` became optional after the release of Custom Sidebar feature. This PR makes this field optional in CLI.
Sync CMA validation with cli validation
> fix(extensions): Make fieldTypes property optional

- lib/cmds/extension_cmds/create.js
- lib/cmds/extension_cmds/update.js
Fixes a bug in `contentful extension create` and `contentful extension update` introduced in v0.19.0
Don't use default values for `type: array`
> fix(extensions): Fix incorrect default value for fieldTypes

- lib/cmds/space_cmds/export.js
Fixes Isssue 117:
If an environment-id is stored previously using ```contentful space environment use```, the export function does not use it.
The bug was due to the environment-id command line argument having a default value of "master". Removed the default and replaced it with a check against the context, just like for store-id.
[Issue 117](https://github.com/contentful/contentful-cli/issues/117)
> fix(space export) Use previously stored environment-id

- docs/content-type/list/README.md
- lib/cmds/content-type_cmds/list.js
- lib/cmds/space_cmds/environment_cmds/list.js
- test/unit/cmds/content-type_cmds/list.test.js
Be more Environment aware.
- Get content types via the environment vs space
- Add new option, environment id, to specify the environment when listing content types
- Update content type list cmd documentation with new options
- Given the environment driven context, certain methods would only be available by an environment object hence deprecation warnings
- Valuable to have context on which environment is active and which one is currently on when listing content types.
- Nice to have, being able to list content types from a specific environment without having to switch to that environment.
> Address deprecated function warning when listing content types

- lib/cmds/space_cmds/migration.js
- package-lock.json
- package.json
Allow for migrations to happen with a quiet mode
- Add option `--quiet, -q` to the usage params
The [Contentful Migration](https://github.com/contentful/contentful-migration) package now supports a quiet mode. Hence, Contentful Cli needs to be updated accordingly.
-   [x] Implemented feature
> Add --quiet option for migrations

- lib/context.js
This PR changes `.contentfulrc.json` look up order. 
*Current behavior*: `.contentfulrc.json` located in `home` folder trumps config located in `process.cwd()`
*New behavior*: script tries to find `.contentfulrc.json` in `process.cwd()` (and then looks one folder up in a tree, recursively). if there's no `.contentfulrc.json` in a tree, then `home` folder is used.
It's convenient to collocate config with a project you're currently working on and be able to jump between projects without a need to change configuration in global configuration file.
Current behavior complicates the flow for extensions development using [create-contentful-extension](https://github.com/contentful/create-contentful-extension).
> feat(config): change config look up order

- .gitignore
- lib/cmds/extension_cmds/create.js
- lib/cmds/extension_cmds/delete.js
- lib/cmds/extension_cmds/get.js
- lib/cmds/extension_cmds/list.js
- lib/cmds/extension_cmds/update.js
- lib/cmds/extension_cmds/utils/log-as-table.js
- test/integration/cmds/extension/__snapshots__/create.test.js.snap
- test/integration/cmds/extension/__snapshots__/delete.test.js.snap
- test/integration/cmds/extension/__snapshots__/update.test.js.snap
- test/unit/cmds/extension_cmds/create.test.js
- test/unit/cmds/extension_cmds/get.test.js
- test/unit/cmds/extension_cmds/update.test.js
Fixing the fact that all extensions related commands didn't respect `activeEnviromentId`.
Right now all extensions commands uses `master` environment if user didn't specify `--environment-id` as an argument of the command. 
It's misaligned with `space-id` logic which respects `activeSpaceId`.
> fix(extensions): all extensions cmd should respect activeEnviromentId

- lib/cmds/space_cmds/use.js
Change the note for the CLI user that master will be used as the default environment.
The `use` command sets the default space for following actions. The notice should state that the `master` environment is used as the default environment if no `--environment-id` parameter has been set.
> Change the meaning of notice for user

- package-lock.json
- package.json
There was a semantic-release/manual release mix up with contentful-import, so after 7.5.0, version 7.4.4 was published. It includes all the required changes.
This new version of contentful-import points to an updated version of the cma SDK, which includes a fix for passing httpAgent on ratelimit retries.
> fix(contentful-import): bump dependency of contentful-import

- lib/cmds/login.js
There was an update on your backend that changed the token format which broke the cli validation
Fixes #138
> fix: Update token regex

- lib/cmds/space_cmds/migration.js
- test/unit/cmds/space_cmds/migration.test.js
Before, the migration CLI would not pick up the access token passed from `contentful-cli`, instead it would use its own mechanism to resolve `~/.contentfulrc.json`. This was caused by the migration CLI using a [different property name for the access token][1].
[1]: https://github.com/contentful/contentful-migration/blob/master/src/bin/lib/config.ts#L9
> fix(migration): Pass access token correctly to migration lib

- package.json
While the tests pass, the build fails because Circle CI runs out of memory. This PR attempts to resolve this issue.
> Address Circle CI failing build

- README.md
Explain a new install method
There's now https://formulae.brew.sh/formula/contentful-cli to install this tool
To tell people about the new install method
> chore: Add homebrew install method

- docs/login/README.md
- lib/cmds/login.js
- test/integration/cmds/login.test.js
- test/unit/cmds/login.test.js
Helps with #37 
Added the `--management-token` flag to the login command.
Added the `--management-token` flag to the login command. This helps when specifying the `managementToken` directly (e.g. for use in ci or headless systems).
This helps with the problems mentioned in #37 .
> feat(commands): Add --management-token flag to login command

- lib/cmds/space_cmds/environment_cmds/use.js
- lib/config.js
Fixes a bug with the interactive `space use` command, reported by @suevalov .
Fixes a bug reported by @suevalov .
The interactive `space use` and `space use environment` command was not working.
Added the `space use` to the whitelist and made the `--environment-id` flag optional for the `space use environment` command.
Fixes a bug reported by @suevalov .
> fix: space use interactive mode

- .circleci/config.yml
- package-lock.json
- package.json
- script/bump-brew-formula.sh
This adds a script to ci to automatically bump the brew formula to the newest version when merged to master.
Added script to enable ci to create a pr in the `/Homebrew/homebrew-core` repo. This bumps the brew formula to the newest version.
Automatically bump brew formula.
> feat: Automatically bump brew formula in ci

- lib/cmds/content-type_cmds/get.js
- lib/cmds/space_cmds/generate_cmds/migration.js
- lib/cmds/space_cmds/import.js
- lib/cmds/space_cmds/migration.js
Removes static `default` set within yargs `environment-id` option to prevent the active environment from being overriden. 
The active environment value is used for the `contentful space export` command (thanks to #119), but ignored for several other commands. This PR removes all occurrences of `default: 'master'` in yargs `environment-id` options.
Fixes #160
> Fix: use active environment as default

- lib/cmds/space_cmds/environment_cmds/use.js
- lib/cmds/space_cmds/use.js
Fixes misleading error message for `contentful space use --space-id`.
Command `contentful space use --space-id`, entered without `space-id` lets you choose interactively from your spaces.
Fixes misleading error message for `contentful space use --space-id`.
> Added arg type to fix wrong cast to boolean

- lib/cmds/space_cmds/generate_cmds/migration.js
- test/unit/cmds/space_cmds/generate_cmds/migration.test.js
Update `generate migration` command to use `changeFieldControl` instead of deprecated `changeEditorInterface`.
Replaced `changeEditorInterface` with `changeFieldControl`, added the `widgetNamespace`. 
Warnings when generating a migration script mentioned in #180
> fix(migration): Update migration to use changeFieldControl

- .circleci/config.yml
- package.json
This adds the binaries to the release assets and bumps their node version to 12
During support, the need for downloadable binaries was expressed.
> fix(release): Add binaries to release

- .circleci/config.yml
- package-lock.json
`--ignoreLow` flag is deprecated in npm-audit-resolver (see [issue](https://github.com/naugtur/npm-audit-resolver/issues/19)), so slack was receiving a warning from the cli that it was failing this check due to low risk vulns.
This PR updates the audit check and, while we're at it, updates dependencies.
> chore(audit): update audit check to use moderate audit level

- .gitignore
- lib/cmds/config_cmds/add.js
- lib/cmds/config_cmds/remove.js
- lib/context.js
- lib/utils/contentful-clients.js
- lib/utils/middlewares.js
- test/integration/cmds/config/add.test.js
- test/unit/utils/middlewares.test.js
feat: Adds a hidden config option for passing 'insecure' to the client, allowing for local development
feat: Allow specifying the config file path in environment with `CONTENTFUL_CONFIG_FILE`
> feat(config): allow disabling TLS on clients

- lib/cmds/login.js
Masks token pasting when logging in. Previous pull request was breaking circleci for some reason
Uses input type "password" instead of "input" as we're dealing with secret tokens.
Security focused where tokens aren't availabe in CLI output logs.
> fix(login-input): Mask token paste input

- lib/cmds/space_cmds/migration.js
This attempts to fix a bug caused by a breaking yargs change (yargs parser now throws on invalid config)
> fix(migration): do not use strict mode

- lib/cmds/space_cmds/export.js
- lib/cmds/space_cmds/import.js
- lib/utils/proxy.js
Proxy args are represented internally as an object in most cases (when loaded from config, when loaded from the ENV..), but must be passed to other cli tools (export/import/migration) as strings. In the case where the proxy arg is from the command line and the call is for export/import (migration doesn't support the proxy command line arg) the string arg was treated as an object, and so using the arg would lead to an error. This change passes the string directly.
(the unrelated change with management* is just to make export more closely match import)
> fix(args): proxy must be passed as a string to export/import/migration

- .circleci/config.yml
Circleci is deprecating xcode images for v9.0. I don't see a reason that xcode has to be at this old version in order to run our `bump brew formula` step, so I'm updating it without further changes. I'm making this a "fix" so that we can test that the release step and homebrew step work correctly.
> fix(circle): update xcode for bump-brew-formula CI step

- .circleci/config.yml
This fixes an invalid circle config which was pushed to master
> fix(circleci): increase no-output-timeout for bump-brew step

- .circleci/config.yml
Finally fix this brew formula thing since upgrading the xcode version there.
> fix(config): add no output timeout to bump-brew-formula CI step

- lib/cmds/space_cmds/alias_cmds/list.js
For more than one alias, the old attempted sorting would break as there is no name property to refer to. We now sort by id to fix this.
> fix(aliases): sort by id instead of name

- docs/space/import/README.md
[Contentful-import](https://github.com/contentful/contentful-import) (and thus `contentful space import`) does not support importing roles. This PR updates the docs to make that clear.
> docs(import): `contentful space import` does not import roles

- .circleci/config.yml
Homebrew-core is now a shallow clone in our brew step, now we explicitly fetch with the --unshallow option 
Context: https://github.com/Homebrew/brew/pull/9383
> fix(ci): address shallow cloning for homebrew

- .circleci/config.yml
Currently, we're running the script on every push:
The task es very time consuming and also downloads > 500MB
Since there is no benefit in doing it other than for releases, we will filter by branches now
> fix(build): only run brew formula update on release

- package-lock.json
- package.json
Bump contentful export version:
This export version will handle assets that were not successfully processed and notify the user of which of them had issues.
> fix(export-assets): bump contentful export version

- .circleci/config.yml
- package.json
In order to properly use other experimental versions of our packages, we need a new channel here too.
> chore: release experimental branch

- lib/cmds/space_cmds/environment_cmds/create.js
To account for environments for which creation takes longer than 30 seconds, we increase the number of retries that environment processing status is checked.
> feat(env-creation): increase retry default for env processing check

- docs/space/environment/create/README.md
- lib/cmds/space_cmds/environment_cmds/create.js
- package.json
- test/integration/cmds/space/environment/__snapshots__/create.test.js.snap
Add optional option to provide a specified timeout in minutes for `--await-processing` upon environment creation.
**Open Issues**
- We should add a test [here](https://github.com/contentful/contentful-cli/blob/master/test/unit/cmds/space_cmds/environment_cmds/create.test.js) that checks that `environmentCreate` triggers `checkAwaitProcessing` with the correct parameters. How to mock that correctly?
- Snapshot tests behave flaky locally.
> feat(env-creation): add processing-timeout option

- lib/cmds/space_cmds/environment_cmds/create.js
Informe users when environment processing is not ready and the awaiting time is over
> fix(env-creation): awaiting processing timeout message

- lib/cmds/content-type_cmds/get.js
allows `-e` flag in `contentful ct get` command as it is in `contentful ct ls`
`-e` alias for `--environment-id` is available for `contentful content-type ls` but not for `contentful content-type get`
I'd like to be able to use the `-e` alias for `environment-id` in the `contentful ct get` command as it is with the `contentful ct ls` command.
- invalid:
`contentful ct get -s ********* -e sandbox --id *********`
- valid:
`contentful ct ls -s ********* -e sandbox`
- valid:
`contentful ct get -s ********* --environment-id sandbox --id *********`
it will bring consistency to `contentful ct` / `contentful content-type` and expedite the command.
```
→ contentful ct get -h
ct get
Show a content type
Options:
-h, --help                Show help                                  [boolean]
--id …
```
> add `e` alias to `environment-id` flag

- .github/dependabot.yml
Adds dependencies to dependabot ignore list
All ignored dependencies are now pure ESM packages. This PR lets dependabot ignore them for now in order to declutter the open pull requests. However, we shoud consider a rewrite to ESM or making changes to support pure ESM packages (e.g. like described [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)).
> chore(dependabot): ignore dependencies

- lib/cmds/space_cmds/export.js
- test/unit/cmds/space_cmds/export.test.js
Add delivery-token param to the param list for the export command. We already support this command but it was not listed so far.
> feat(params): Add delivery-token param to export cmd [ZEND-1938]

- .github/dependabot.yml
- lib/utils/markdown.js
- package-lock.json
- package.json
- ~Since version 4, marked is a pure ESM package and therefore supposed to be ignored for now: https://github.com/contentful/contentful-cli/blob/master/.github/dependabot.yml#L27 This PR is blocked until we have added support for pure ESM packages.~
- ~Align on reasoning for https://github.com/contentful/contentful-cli/pull/1266~
- ~See also: https://github.com/contentful/contentful-cli/issues/1337~
Above issues are resolved, it's fine to use v4 with commonjs. See also [here](https://github.com/markedjs/marked/issues/2380#issuecomment-1030133024)
> chore: upgrade marked

- docs/space/import/README.md
Update docs to account for missing parameters.
- double check that `.contentfulrc` values won't be overwritten by newly introduced default. If so, revert. (Reverted.)
> chore(docs): add retry-limit and timeout parameter to docs []

- docs/space/README.md
- docs/space/accesstoken/create.md
- docs/space/accesstoken/list.md
- lib/cmds/space_cmds/accesstoken_cmds/list.js
- test/unit/cmds/space_cmds/accesstoken_cmds/list.test.js
Add a `silent` parameter to the `contentful space accesstoken list` command in order to print out the raw JSON result.
[Feature request](https://github.com/contentful/contentful-cli/issues/1476)
> feat(accesstoken_cmds): Add silent output for accesstoken list

- docs/space/accesstoken/create.md
- lib/cmds/space_cmds/accesstoken_cmds/create.js
- test/unit/cmds/space_cmds/accesstoken_cmds/create.test.js
Add environment flag to `space accesstoken create` command to specify which environment the accesstoken will have access to. Defaults to master if omitted. 
[Feature request](https://github.com/contentful/contentful-cli/issues/1390)
> feat(accesstoken): Add environment flag to accesstoken create command

- .circleci/config.yml
- .eslintrc.js
- .gitignore
- bin/contentful.js
- lib/cli.ts
- lib/utils/middlewares.js
- package-lock.json
- package.json
- tsconfig.json
Initialise typescript and allow commonjs and esm to co-exist
This PR introduces typescript to the codebase, it'll allow us to work with esm, and commonjs 
Next we will configure tests to be working with typescript as well.
> feat: init typescript

- package.json
`pkg`, which builds standalone executables of Contentful CLI for Windows, Mac, Linux, was still using Node 12. Upgraded to Node 16.
> feat: upgrade node versions used by pkg to build standalone executables

- lib/cmds/space_cmds/create.ts
- package-lock.json
- package.json
- test/integration/cmds/space/__snapshots__/create.test.js.snap
Contentful management js lib types was not showing `defaultLocale` as an available option in `createSpace` method.
That led to removing it in #1583  See https://github.com/contentful/contentful-cli/pull/1583#discussion_r957541315
This PR adds the options back `contentful space create --default-locale`
> fix: add defaultLocale as option to space create command

- .contentfulrc.json
- lib/cmds/init.ts
- lib/cmds/login.ts
- lib/utils/async.ts
- lib/utils/token-info.ts
- test/integration/cmds/login.test.js
- Clean up and structure logging messages for `login` command
- Migrate `utils/async.js` to typescript
> chore: clean up login command messaging structure

- lib/cmds/login.ts
- test/unit/cmds/login.test.ts
Add action parameter to login url
Add `action=cli` to login url and test that open function was called with it.
> feat: add action parameter to login url

- lib/cmds/init.ts
- lib/cmds/init/apikey.ts
- lib/cmds/init/space.ts
- lib/cmds/init/success.ts
Previously we were displaying CMA access token in CDA requests code example. Instead we should display CDA access token. This PR does the following:
* Fetch or create CDA preview api access token
* Abstract space creation flow to it's own function for better readability 
- Write e2e tests for init command
- Try out https://github.com/highlightjs/highlight.js#nodejs-on-the-server instead of the old cli-highlights, fix and test code examples
> feat: fetch and display CDA api preview key in code examples

- .circleci/config.yml
- .gitignore
- bin/contentful.js
- lib/cmds/organization.ts
- package-lock.json
- package.json
- tsconfig.json
This PR introduces support for Typescript to the project. It introduces one new dependency - tsc.
The new build flow consists now of transpiling the whole project to `output` directory and later it's build to a single executable with pkg as before
> feat: add typescript support [SDK-2439]

- package.json
Include output files inside the package
This should fix this issue: https://github.com/contentful/contentful-cli/issues/1795
> fix: include output in package files []

- .circleci/config.yml
- .contentful/vault-secrets.yaml
We added vault support in `master` but didn't rebase `beta` after it. This PR adds it so we can release beta versions
> Chore: Update beta branch with vault []

- lib/cmds/merge.ts
- lib/cmds/merge_cmds/export.ts
- package.json
- test/integration/cmds/__snapshots__/main.test.js.snap
Adds the scaffold to add commands to the `merge` subcommand and the initial `merge export` command with source and target envs
> Feat: Add `merge` command and initial `export` subcommand 

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
Due to pending work needing to be done this PR modifies the name back to `contentful-cli` so we can release a new major with all the new changes that live in beta and weren't released.
This commit [contentful/contentful-cli@`8904c1a` (#1819)](https://github.com/contentful/contentful-cli/pull/1819/commits/8904c1a14ddf334ae9c8d9e522e98eb4dd61d066) should force a new relase by semantic-release
Branches out of beta only adding a new commit to change the package name back
> Chore: merge beta keeping old name []

- README.md
Fixes a typo in the npm package name in the readme. Tripped me up when I copy/pasted the install command.
> docs(readme): Fix contentful-cli npm package name

- .jest/setup.js
- jest.config.js
- lib/cmds/merge.ts
- lib/cmds/merge_cmds/export.ts
- lib/utils/app-installation.ts
- lib/utils/contentful-clients.js
- test/integration/cmds/__snapshots__/main.test.js.snap
- test/integration/cmds/merge/__snapshots__/export.test.ts.snap
- test/integration/cmds/merge/export.test.ts
- test/integration/util.js
- test/unit/cmds/merge_cmds/export.test.ts
- test/unit/utils/app-installation.test.js
This is a redo of #1815 with the new beta branch.
For the upcoming commands we need to check if the merge app is installed in the user provided environments.
Adds the flow check if app is installed in the env and if it isn't and the users confirms it goes ahead and installs it
> feat: add app installation before export [SDK-2441]

- catalog-info.yml
This PR will enable CI alerts to let the team know when the default branch is broken and needs fixing.
Those alerts will be send to the team internal Slack channel.
> chore: send ci alerts to the slack [SDK-2507]

- jest.config.js
Increase global jest timeout as we saw several integration test run failing.
> chore: increase jest timeout to fix integration test pipeline

- .circleci/config.yml
- package-lock.json
- package.json
- test/e2e/__snapshots__/basics.test.js.snap
Bring back standalone builds upon request.
Solves [#1833](https://github.com/contentful/contentful-cli/issues/1833)
**Important:**
We have to add `axios` CJS file explicitly as asset, because `pkg`. can't handle ESM modules.
https://github.com/vercel/pkg/issues/1822
(If this still causes problems, we have to downgrade to < 1)
> feat: standalone CLI [SDK-2554]

- package.json
We additionally have to add the standalone builds to the GitHub release.
This is a follow up for #1893
> fix: git release of standalone apps [NONE]

- .circleci/config.yml
Hopefully the very last bit of getting the standalone back on the releases.
> fix: pack standalone builds before release [NONE]

- package-lock.json
- package.json
This PR in `contentful-import` fixes an error where you can get 422 when uploading assets https://github.com/contentful/contentful-import/pull/747/files.
This is just the bump to use that version of the package
> fix: update contentful-import to fix https regex []

- .circleci/config.yml
- package.json
There have been problems with printing out the package version https://github.com/contentful/contentful-cli/issues/1800
This PR moves the building of the package to the prePublishOnly script so that the version is correctly set by semantic-release before it is bundled up.
> fix(): correct version being used in CLI package [PHX-2553]

- lib/cmds/merge_cmds/show.ts
- lib/utils/merge/types.ts
Temporary filter to only show content type changes, while editor interfaces are not supported yet.
> feat: only show content type changes in merge show command [PHX-2514]

- lib/cmds/merge_cmds/export.ts
- package-lock.json
- package.json
- test/unit/cmds/merge_cmds/export.test.ts
This uses the [new reworked function](https://github.com/contentful/contentful-management.js/pull/1812) to call an app action and wait for its response.
> fix: ensure settled action result before fetching it [PHX-2608]

- lib/utils/proxy.js
- test/proxy/client.js
Since the last upgrade of `https-proxy-agent` dependency it is being imported incorrectly thus causing an error on proxy setup when not using `rawProxy: true`
> fix: proxy agent import [PHX-2711]

- package.json
I am pretty sure >= 8 is already not working anymore.
> chore: inform on actual engine compatibility (>= 16)

- lib/utils/merge/create-merge-message.ts
- lib/utils/merge/render-changeset-messages.ts
- lib/utils/merge/utils.ts
- test/unit/utils/merge/merge-mock.ts
- test/unit/utils/merge/print-changeset-messages.test.ts
During the `merge show` command, move operations are now also displayed.
For field moves, we indicate the direction (up or down). 
For more deeply nested moves, we indicate that the order has changed and list the (nested) properties.
The screenshot shows the following cases: 
- nested property has order changes
- deeply nested property has order changes
- field was moved up
- field was moved down
> feat: show moves in merge show command output [PHX-2582]

- .circleci/config.yml
Updating the Xcode version & adding a Gen2 resource class because CircleCI is deprecating MacOS intel Gen1.
This one [will be deprecated in January 2024](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718), so by then we'll have to switch to a silicon mac resource class.
> chore(): update xcode version

- lib/cmds/login.ts
- test/unit/cmds/login.test.ts
Use host from config in login command, this will allow users to login to EU accounts via CLI
> feat: use host in login [PHX-2805]

- .circleci/config.yml
See https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md - the "release" CI job that executes semantic-release requires a node version >=20.8.1. 
I don't believe it is necessary to update the other jobs to this node version at this time, just this one should be sufficient.
master builds have been stuck due to this issue
> chore: bump 'release' CI job node version to make it compatible with semantic-release

- package-lock.json
- package.json
Previous attempts at enabling users to override the default API `host` for EU data residency purposes, did not propagate the changes to the downstream `contentful-migration` tool. That functionality was added to `contentful-migration` [here](https://github.com/contentful/contentful-migration/pull/1286) and released in version 4.20.0, so we're bumping our dependency to that version.
> fix (space migrations): bump contentful-migration to allow migrations for EU spaces

- lib/utils/github.js
`contentful space seed` currently throw the following error : 
```
🚨  Error: mkdirp is not a function
```
Related issue : https://github.com/contentful/contentful-cli/issues/1978
Impossible to run seed command
This PR fix this issue and make the function actually works
> fix: seed "mkdirp is not a function" []

- docs/organization/README.md
- docs/organization/export/README.md
- lib/cmds/organization_cmds/export.ts
- lib/config.js
- lib/utils/cursor-pagninate.ts
- package-lock.json
- test/integration/cmds/organization/__snapshots__/export.test.ts.snap
- test/integration/cmds/organization/export.test.ts
- test/unit/cmds/organization_cmds/export.test.ts
Adds a new command to export organization entities. For now this includes only taxonomy data.
As a user, I should be able to run contentful organization export --organization-id <organization-id> and get the export of my taxonomy like:
`{ "taxonomy": { "concepts": [], "conceptSchemes": [] } }`
> feat: organization export 

- lib/cmds/organization_cmds/export.ts
- test/integration/cmds/organization/__snapshots__/export.test.ts.snap
The description says the output directory is `migrations` but later in the code it's `data`
https://github.com/contentful/contentful-cli/pull/2794/files#diff-aac00e876afd4ffa5bd4687076602b890ad5a0d68ea0f30b681052d67ca2a5fcR90
> fix: change description for output file in org export

- README.md
- lib/cmds/space_cmds/export.js
> [!IMPORTANT]  
> Must be merged after https://github.com/contentful/contentful-export/pull/1921 is merged and contentful-export is bumped in this repo
This changeset allows the `contentful space export` command to use a `--host-delivery` flag to point at cdn.eu.contentful.com
> fix: allow host-delivery config to be passed to export command [EXT-5986]

- package-lock.json
- package.json
manual bump to ensure https://github.com/contentful/contentful-export/pull/1953 is released
> fix: bump contentful-export to include asset download fix [ZEND-5790]

- lib/cmds/space_cmds/import.ts
- test/integration/cmds/space/__snapshots__/import.test.js.snap
- test/unit/cmds/space_cmds/import.test.ts
The contentful-import library supports the [--skipContentUpdates](https://github.com/contentful/contentful-import?tab=readme-ov-file#skipcontentupdates-boolean-default-false) and [--skipAssetUpdates](https://github.com/contentful/contentful-import?tab=readme-ov-file#skipassetupdates-boolean-default-false) flags. This change allows these flags to be propagated from the CLI to the import library
> fix: allow --skip-content-updates and --skip-asset-updates import flags [EXT-6233]

- docs/space/export/README.md
- docs/space/import/README.md
It was unclear how a user should use the `contentful space export` and `contentful space import` commands if their space has embargoed assets. This PR adds instructions in the docs for these commands
Add instructions in the appropriate docs files for how to use export and import with embargoed assets.
> chore: update docs with embargoed asset import/export info [DX-63]

- lib/cmds/space_cmds/generate_cmds/migration.js
- test/unit/cmds/space_cmds/generate_cmds/migration.test.js
The `contentful space generate migration` command was failing with the error:
> Error: undefined does not match field "value": string | boolean | null | number | RegExp | BigInt of type Literal
This error caused **all `changeFieldControl` calls to be missing** from generated migration files. Customers reported that previously working migrations were no longer generating complete output, with essential editor interface configurations being omitted entirely.
**Example of missing output:**
```javascript
brand.changeFieldControl("name", "builtin", "singleLine", {});
brand.changeFieldControl("foo", "builtin", "singleLine", {});
brand.changeFieldControl("bar", "builtin", "dropdown", {});
// ... etc
```
The error occurred when editor interface settings contained `undefined` values, which were …
> fix: handle undefined values in migration generation [ZEND-6547]

- docs/space/README.md
- docs/space/environment-alias/README.md
- docs/space/environment-alias/create/README.md
- docs/space/environment-alias/list/README.md
- docs/space/environment-alias/update/README.md
- lib/cmds/space_cmds/alias_cmds/create.ts
- test/unit/cmds/space_cmds/alias_cmds/create.test.ts
This PR adds a new command to allow for creating a new environment alias from the CLI.
Customers will now be able to create a new environment alias from the CLI, for example:
```
contentful space environment-alias create --alias-id 'staging' --target-environment-id 'release-2'
```
Also updated docs for all of the environment-alias commands
The CLI allowed for listing and updating an alias, now customers can add a new alias from the CLI.
Tested a few different scenarios with this new feature:
- Tested this new functionality in US and EU spaces
- Tested when a space doesn't have environment aliases available (returns an error message)
- Tested when a space has reached the limit of available environment aliases (returns an error message)
> feat: add environment-alias create command [DX-370]

- .github/dependabot.yml
Adds dependencies to dependabot ignore list.
Dependencies added to ignore are now pure ESM packages.
This PR lets dependabot ignore them for now in order to declutter the open pull requests. However, we should consider a rewrite to ESM or making changes to support pure ESM packages in the future.
> chore(dependabot): add deps to ignore []
