lib/cmds/config_cmds/add.js, lib/cmds/space_cmds/export.js, lib/cmds/space_cmds/import.js, lib/cmds/space_cmds/seed.js, lib/context.js, lib/utils/contentful-clients.js, test/unit/cmds/space_cmds/export.test.js, test/unit/cmds/space_cmds/import.test.js
This PR adds the ability to have a host to use when connecting the API
=> feat: Add host

README.md, docs/config/add/README.md, docs/config/remove/README.md, lib/cmds/config_cmds/add.js, lib/cmds/config_cmds/remove.js, lib/cmds/space_cmds/export.js, lib/cmds/space_cmds/import.js, lib/cmds/space_cmds/migration.js, lib/cmds/space_cmds/seed.js, lib/context.js, lib/utils/contentful-clients.js, lib/utils/proxy.js, package-lock.json, package.json
Depends on:
* https://github.com/contentful/contentful-import/pull/113
* https://github.com/contentful/contentful-export/pull/118
* https://github.com/contentful/contentful-migration/pull/130
=> feat(proxy): add new raw proxy config option

docs/space/migration/README.md
Just answered a question where a person wasn't aware of the format of the scripts used by migration. A link to the documentation here might help. :)
=> Update documentation for space migration

README.md, lib/cli.js, test/e2e/__snapshots__/basics.test.js.snap, test/integration/cmds/__snapshots__/main.test.js.snap
=> fix(completion): Remove completion command

package-lock.json, package.json, recordings/unnamed-60.json5, recordings/unnamed-61.json5, test/integration/cmds/extension/__snapshots__/create.test.js.snap, test/integration/cmds/extension/__snapshots__/delete.test.js.snap, test/integration/cmds/extension/__snapshots__/update.test.js.snap
Bump contentful-migration to include the editor interface fix
=> fix(migration): Bump contentful-migration

lib/cmds/extension_cmds/create.js, lib/cmds/extension_cmds/get.js, lib/cmds/extension_cmds/update.js, lib/cmds/extension_cmds/utils/log-as-table.js, test/unit/cmds/extension_cmds/__snapshots__/update.test.js.snap, test/unit/cmds/extension_cmds/create.test.js, test/unit/cmds/extension_cmds/get.test.js, test/unit/cmds/extension_cmds/update.test.js
* `update --force` creates new extension there's no extension with a given id
* added space id and link to the extension to `logExtension` function
=>  feature(extension): 'update --force' command creates extension

lib/guide/step-dev-server.js
Minor typo
Minor typo - 'immediatly.' -> 'immediately.'
It solves the problem (First World) of red squigglies. :)
=> fix: Minor typo

test/integration/cmds/space/__snapshots__/import.test.js.snap
Fix for failing snapshot test.
=> Fix snapshot

lib/cmds/boilerplate.js
=> Fix Missing Access Token Error for Boilerplates

lib/cmds/space_cmds/create.js, test/integration/cmds/space/create.test.js, test/unit/cmds/space_cmds/create.test.js
=> Remove sys error when aborting space creation with contentful guide

lib/cmds/space_cmds/alias.js, lib/cmds/space_cmds/alias_cmds/list.js, lib/cmds/space_cmds/alias_cmds/update.js, lib/utils/pagination.js, package-lock.json, package.json, test/integration/cmds/extension/create.test.js, test/integration/cmds/space/__snapshots__/help.test.js.snap, test/unit/cmds/space_cmds/alias_cmds/list.test.js, test/unit/cmds/space_cmds/alias_cmds/update.test.js
Add Environment aliases management
=> feat: Add Environment aliases management

.circleci/config.yml, README.md, audit-resolve.json, package-lock.json, package.json
I updated the node version number from 8 to 12 both in the readme as well as in the circle ci config file. I also fixed a styling issue in the readme.
=> chore(config): update node version from 8 to 12

package.json
=> fix(release): Published assets

.circleci/config.yml, package.json
=> fix(release): Simplify zip release

.circleci/config.yml
After an update [npm-audit-resolver](https://github.com/naugtur/npm-audit-resolver) the command in our CI failed.
=> Fix audit resolver after update

package-lock.json, package.json
Reverts contentful/contentful-cli#219
=> Revert "Bump contentful management version"

docs/login/README.md, docs/space/generate/migration/README.md
Small documentation update for grammar.
The sentence in the migrations section was a bit confusing.
Understanding
None
N/A
=> docs(README): update grammar

package-lock.json, package.json
Updating contentful-migration package to 1.0.13
=> fix(deps): update contentful-migration to 1.0.13

.circleci/config.yml
Temporarily ignore audit check.
=> Ignore audit check

docs/space/export/README.md, lib/cmds/space_cmds/export.js, test/unit/cmds/space_cmds/export.test.js
=> Support include-archive, raw-proxy

package-lock.json, package.json
=> fix(dependencies): Bump contentful-export dependency version

package-lock.json, package.json, recordings/9-tags-not-found.json5, test/integration/cmds/space/import.test.js
=> fix(import): bump contentful-import to 7.9.10

package-lock.json, package.json
Manual update for **contentful-migration** v3 -> v4
=> feat: update migration version to v4

.dependabot/config.yml, package-lock.json, package.json
=> chore: [EXT-2508] pin at husky v4

.circleci/config.yml
Provide context for release related env variables.
=> chore(ci): add context

.circleci/config.yml, package-lock.json, package.json
Use `contentful-migration@experimental` in experimental branch of the CLI. Marked as fix to get a new release.
=> fix: use experimental contentful-migration

package-lock.json, package.json
=> build(deps): bump contentful-migration from 4.0.0 to 4.1.1

README.md
=> chore: remove codecov badge

package-lock.json, package.json
Bump dependency versions
Use latest versions and address npm audit report
=> Bump contentful export version

.github/dependabot.yml, package-lock.json, package.json
Fix tests that were broken by faulty Dependabot merges (e.g. this [PR](https://github.com/contentful/contentful-cli/pull/1127)).
=> fix(tests): Fix broken tests

package-lock.json, package.json
Update contentful-export dependency to 7.17.16 to implement [bugfix](https://github.com/contentful/contentful-export/pull/1047)
=> chore(dep): update contentful-export to 7.17.16 [NONE]

package-lock.json, package.json
Update/Downgrade dependencies to fix known security vulnerabilities.
=> fix(sec): update dependencies to fix sec vulns [NONE]

.circleci/config.yml
Update the (deprecated) Xcode image to fix CI/CD pipeline
=> fix(build): update xcode version [NONE]

package-lock.json, package.json
Remove unused dependency `trevor` from deps list, and related unused script command.
=> chore: audit dependencies [NONE]

lib/cmds/init.ts, lib/cmds/init/greetings.ts, lib/config.js, package-lock.json, package.json, test/integration/cmds/__snapshots__/main.test.js.snap, test/integration/cmds/init.test.js
Add `init` command basic structure
* Clone the branch locally
* run `npm link && npm tsc:watch`
* then run `contentful init`
* You should see Contentful welcome message
=> feat: add init command

package-lock.json, test/integration/cmds/extension/create-update-delete.test.js, test/integration/util.js
Reverts contentful/contentful-cli#1588
=> Revert "build(deps-dev): bump eslint-plugin-jest from 26.8.1 to 26.8.3"

lib/cmds/login.ts
Wait for access token to be displayed to avoid race condition
**Before**
**After**
=> fix: wait for access token before prompting space

lib/cmds/init.ts, lib/cmds/space_cmds/use.ts
Inject management token to context before passing it to space import, use, or create. This to fix:
=> fix: inject management token in context

lib/cmds/init.ts, lib/cmds/init/greetings.ts, lib/cmds/init/space.ts, lib/cmds/init/success.ts, lib/cmds/space_cmds/use.ts
Improve CDA code examples for React, GraphQL, Contentful.js, and REST API
**React**
**GraphQL**
**Contentful.js**
**REST API**
=> fix: improve CDA code examples

.circleci/config.yml, .contentful/vault-secrets.yaml, .github/workflows/dependabot-approve-and-request-merge.yml
Initializes config for CF vault
=> feat(): Initialize CF vault 

.circleci/config.yml
Add CF vault config to improve env variable management
=> feat(): add cf vault config []

.circleci/config.yml
Update CircleCI version in config
=> fix(): update circleci version

lib/utils/app-installation.ts, test/unit/utils/app-installation.test.js
Add a utils function that checks if a specified app is installed on an environment.
=> Feat/app installation check [SDK-2440]

.circleci/config.yml, package-lock.json, package.json, test-integration.sh, tsconfig.json
* Remove `tsConfig` comments
* Remove `linux` and `osx` build step commands
* Remove unused `parcel` package
* Remove unused `trevor` package
* Remove unused `test-integration.sh` script
* Run `npm audit` only on production dependencies
=> chore: cleanup leftover code

.github/workflows/update-branch.yml
This adds a github action that rebases beta every night so we can have an update branch to work on
=> feat: add action to rebase beta automatically [SDK-2504]

.circleci/config.yml
Hopefully the very last bit - we also have to build the standalone apps before we release it 🙈
=> fix: build standalone app before build [NONE]

docs/merge/README.md, docs/merge/export/README.md, docs/merge/show/README.md, lib/cmds/merge_cmds/export.ts, lib/cmds/merge_cmds/show.ts, lib/utils/merge/prepare-merge-command.ts, lib/utils/merge/types.ts, test/integration/cmds/merge/__snapshots__/show.test.ts.snap, test/integration/cmds/merge/export.test.ts, test/integration/cmds/merge/show.test.ts
Additional changes:
- introduce Readme files for merge commands
- extract shared merge command setup logic into a helper function.
=> feat(merge): use new cmd param alias

lib/cmds/merge_cmds/export.ts, lib/cmds/merge_cmds/show.ts, lib/utils/app-actions.ts, lib/utils/merge/errors.ts, test/unit/cmds/merge_cmds/export.test.ts, test/unit/cmds/merge_cmds/show.test.ts
Right now when we have a `PollTimeout` error the output is not the best. This fixes it and sets more user friendly messages.
=> fix: better errors on merge cli commands []

package-lock.json, package.json, test/integration/cmds/merge/export.test.ts, test/integration/cmds/merge/show.test.ts
Updates the `@contentful/app-action-utils` to the latest version to make sure the `merge` commands work
=> feat: update app action utils to latest []

package-lock.json, test/integration/cmds/merge/export.test.ts
to fix:
And adjusting failing test related to app actions which times out
=> chore: fix sync issue on package-lock files

lib/utils/merge/create-merge-message.ts, test/unit/utils/merge/print-changeset-messages.test.ts
This PR implements the new designs for the CLI output of the `merge show` command.
Main changes: color, indentation, display of added field values
Left: previous layout
Right: new layout
=> feat: implement new layout for merge show command

README.md
demonstrate how to configure the CLI for EU usage
=> docs: add docs for configuring the CLI for EU DR

.circleci/config.yml, README.md, package-lock.json, package.json
=> Update branch name from master to main

.github/CODEOWNERS
=> chore: [MEC-5742] Update CODEOWNERS

.github/CODEOWNERS
=> chore: move ownership to DX

package-lock.json, package.json
Ship the fix for experiences that was introduced in https://github.com/contentful/contentful-migration/pull/1320
=> fix: bump contentful-migration from 4.20.2 to 4.21.0 [SPA-2047]

.github/CODEOWNERS
Dependabot should not need to wait for codeowner approval to merge PRs.
=> fix: un-own package jsons to allow dependabot to merge PRs []

package-lock.json, package.json
Bump contentful import to fix tag import bug
=> chore: bump contentful import [ZEND-5557]

.circleci/config.yml, .github/dependabot.yml, package-lock.json, package.json
- downgrade and pin semantic-release to node18 compliant version
=> Fix/soc2 vulns [EXT-5915]

package-lock.json
Npm audit is reporting issue with a dependency
=> fix: npm audit vulnerability [GROOT-1789]
